// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMC0j8zGiw9v2mFm2wcpZXkLiS9LxoFSY',
    appId: '1:630385136368:android:79086f447b9c692dcf2835',
    messagingSenderId: '630385136368',
    projectId: 'electric-vehicle-10272',
    storageBucket: 'electric-vehicle-10272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANczb0CW7-lSq4XN9U0NIB4VMlXFnyM-I',
    appId: '1:630385136368:ios:355b42d6d8e29223cf2835',
    messagingSenderId: '630385136368',
    projectId: 'electric-vehicle-10272',
    storageBucket: 'electric-vehicle-10272.appspot.com',
    androidClientId: '630385136368-n1cfijiahunmn9gvasp7gomte0rvaost.apps.googleusercontent.com',
    iosClientId: '630385136368-ig3ve08o6bj6udp2e0cqcmi7b7uphe31.apps.googleusercontent.com',
    iosBundleId: 'com.example.electricVehicle',
  );
}
