name: electric_vehicle
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# --------------------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: 0.13.6
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.0.10
  geolocator: ^10.1.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_datetime_picker: ^1.5.1
  provider: ^6.1.1
  google_fonts: any
  time_slot: ^0.0.3
  printing: ^5.12.0
  pdf: ^3.10.8

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  custom_info_window: ^1.0.1
  floating_action_bubble: ^1.1.4

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.5
  maps_launcher: ^2.2.0

  flutter_riverpod: any
  im_stepper: any

  table_calendar: ^3.0.1
  shared_preferences: ^2.2.2

  #--------------------------- ./PACKAGES END -----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # -------------------------- LOCAL ASSETS ----------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/user/
    - assets/images/station/
    - assets/images/vehicle/
    - assets/images/admin/login/
    - assets/images/admin/station_info/
    - assets/images/admin/port/
    - assets/images/admin/report/

  # -------------------------- LOCAL ASSETS ----------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

